### ISSUE TITLE
Missed setup section

### ISSUE THREAD

**Issue by g4s8** [dgroup/docker-unittests#154]
Usually, docker images doesn't have some testing tools installed, e.g. it may not have `curl` tool,
it would be good feature to add `setup` section to yaml file to install all required tools, e.g.:
```yaml
version: 1
setup:
  - "apk add --no-cache curl"
tests:
  - test:
      assume: "returns OK"
      cmd: "curl -I -s http://localhost/ | head -n 1"
      output:
        - contains: "200 OK"
```
